
finger01:
	g++ -o finger finger01.cc -lcgmuduo -lpthread -g

finger02:
	g++ -o finger finger02.cc -lcgmuduo -lpthread -g

finger03:
	g++ -o finger finger03.cc -lcgmuduo -lpthread -g

finger04:
	g++ -o finger finger04.cc -lcgmuduo -lpthread -g


clean:
	rm -f finger